import { FilesetResolver, PoseLandmarker, DrawingUtils } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14';

const course=document.querySelector('#course'), webcam=document.querySelector('#webcam'), canvas=document.querySelector('#skeleton'), ctx=canvas.getContext('2d');
const start=document.querySelector('#startButton'), restart=document.querySelector('#restart'), recal=document.querySelector('#recalibrate'), layer=document.querySelector('#startLayer'), hud=document.querySelector('#hud');
const command=document.querySelector('#command'), status=document.querySelector('#status'), scoreEl=document.querySelector('#score b'), comboEl=document.querySelector('#combo'), success=document.querySelector('#success'), notice=document.querySelector('#notice');
let pose, drawing, baseline=null, samples=[], score=0, combo=0, lastVideo=-1, played=new Set(), active=true;
const cues=[
 {id:'jump1',a:7,b:11,label:'JUMP!',action:'jump'}, {id:'left1',a:11,b:15,label:'LEFT!',action:'left'}, {id:'duck1',a:15,b:19,label:'DUCK!',action:'duck'}, {id:'dodge',a:19,b:23,label:'DODGE!',action:'dodge'},
 {id:'jump2',a:23,b:24.2,label:'JUMP!',action:'jump'}, {id:'left2',a:24.2,b:25.2,label:'LEFT!',action:'left'}, {id:'right2',a:25.2,b:26.2,label:'RIGHT!',action:'right'}, {id:'duck2',a:26.2,b:27.3,label:'DUCK!',action:'duck'}];
function currentCue(){return cues.find(c=>course.currentTime>=c.a&&course.currentTime<c.b)}
function setMessage(){const c=currentCue();command.textContent=c?c.label:course.currentTime<3?'READY...':course.currentTime>27?'GOAL!':'RUN!';}
function points(l){const sh=(l[11].y+l[12].y)/2, hip=(l[23].x+l[24].x)/2, vis=Math.min(l[11].visibility??1,l[12].visibility??1,l[23].visibility??1,l[24].visibility??1);return {sh,hip,vis}}
function recalibrate(l){samples.push(points(l));if(samples.length<20)return;baseline={sh:samples.reduce((n,p)=>n+p.sh,0)/samples.length,hip:samples.reduce((n,p)=>n+p.hip,0)/samples.length};samples=[];status.textContent='準備OK！映像に合わせて動こう';}
function matches(action,p){if(!baseline||p.vis<.55)return false;const dx=p.hip-baseline.hip, dy=p.sh-baseline.sh;if(action==='jump')return dy<-.055;if(action==='duck')return dy>.075;if(action==='left')return dx<-.075;if(action==='right')return dx>.075;if(action==='dodge')return Math.abs(dx)>.09;return false}
function hit(c){played.add(c.id);score+=100+combo*25;combo++;scoreEl.textContent=score;comboEl.textContent='×'+Math.max(1,combo);success.textContent='GREAT!';success.classList.remove('flash');void success.offsetWidth;success.classList.add('flash');status.textContent='成功！ 次の指示を見よう';}
function tick(){if(!active)return;requestAnimationFrame(tick);if(!pose||webcam.readyState<2)return;const now=performance.now();if(now===lastVideo)return;lastVideo=now;const r=pose.detectForVideo(webcam,now);canvas.width=webcam.videoWidth;canvas.height=webcam.videoHeight;ctx.clearRect(0,0,canvas.width,canvas.height);if(!r.landmarks?.length){status.textContent='全身がカメラに入る位置へ';return}const l=r.landmarks[0];drawing.drawConnectors(l,PoseLandmarker.POSE_CONNECTIONS,{color:'#52e4ff',lineWidth:3});drawing.drawLandmarks(l,{color:'#ffb43d',radius:3});const p=points(l);if(!baseline){recalibrate(l);status.textContent='ニュートラル姿勢を読み取り中…';return}const c=currentCue();if(c&&!played.has(c.id)&&matches(c.action,p))hit(c);setMessage();}
async function boot(){try{notice.textContent='姿勢認識モデルを読み込み中…';const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');pose=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task'},runningMode:'VIDEO',numPoses:1});drawing=new DrawingUtils(ctx);const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:false});webcam.srcObject=stream;await webcam.play();layer.hidden=true;hud.hidden=false;restart.disabled=false;recal.disabled=false;course.currentTime=0;await course.play();notice.textContent='';active=true;tick()}catch(e){console.error(e);notice.textContent='カメラまたは姿勢認識を開始できませんでした。localhost/HTTPSで開き、カメラ許可を確認してください。'}}
start.addEventListener('click',boot);restart.addEventListener('click',()=>{played.clear();score=0;combo=0;baseline=null;samples=[];scoreEl.textContent=0;comboEl.textContent='×1';course.currentTime=0;course.play()});recal.addEventListener('click',()=>{baseline=null;samples=[];status.textContent='まっすぐ立ってください'});course.addEventListener('ended',()=>{command.textContent='GOAL!';status.textContent=`FINISH! SCORE ${score}`;active=false});
